(() => {
  'use strict';
  const A = window.TianShuAuth;
  const tbody = document.querySelector('#memberTableBody');
  const searchInput = document.querySelector('#memberSearch');
  const statusFilter = document.querySelector('#memberStatusFilter');
  const planFilter = document.querySelector('#memberPlanFilter');
  const summary = document.querySelector('#adminSummary');
  const STATUS_LABELS = { pending: '待審核', active: '已啟用', suspended: '已停權' };
  const PLAN_LABELS = { free: '一般會員', formal: '正式會員', permanent: '永久會員' };
  let rows = [], currentUserId = null, started = false, session = null;
  const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  function fmtDate(v){ if(!v)return'—'; const d=new Date(v); return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short'}).format(d); }
  function dateInputValue(v){ if(!v)return''; const d=new Date(v); if(Number.isNaN(d.getTime()))return''; const x=new Date(d.getTime()-d.getTimezoneOffset()*60000); return x.toISOString().slice(0,10); }
  function filtered(){ const q=(searchInput?.value||'').trim().toLowerCase(), st=statusFilter?.value||'', pl=planFilter?.value||''; return rows.filter(r=>{const hay=`${r.email||''} ${r.display_name||''} ${r.role||''} ${r.status||''} ${r.plan||''}`.toLowerCase(); return(!q||hay.includes(q))&&(!st||r.status===st)&&(!pl||r.plan===pl);}); }
  function render(){ if(!tbody)return; tbody.innerHTML=filtered().map(r=>`<tr data-id="${esc(r.id)}"><td><strong>${esc(r.display_name||'未填姓名')}</strong><small>${esc(r.email||'')}</small></td><td><span class="admin-role ${r.role==='admin'?'is-admin':''}">${r.role==='admin'?'管理員':'會員'}</span></td><td><select class="admin-status-select" data-field="status" ${r.id===currentUserId?'disabled':''}>${['pending','active','suspended'].map(v=>`<option value="${v}" ${r.status===v?'selected':''}>${STATUS_LABELS[v]}</option>`).join('')}</select></td><td><select class="admin-plan-select" data-field="plan">${['free','formal','permanent'].map(v=>`<option value="${v}" ${r.plan===v?'selected':''}>${PLAN_LABELS[v]}</option>`).join('')}</select></td><td><input class="admin-date-input" data-field="starts_at" type="date" value="${dateInputValue(r.starts_at)}"></td><td><input class="admin-date-input" data-field="expires_at" type="date" value="${dateInputValue(r.expires_at)}" ${r.plan==='permanent'?'disabled':''}></td><td><small>建立 ${fmtDate(r.created_at)}</small><br><small>更新 ${fmtDate(r.updated_at)}</small></td><td><button type="button" class="admin-save-btn">儲存</button></td></tr>`).join(''); const counts=rows.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{}); if(summary)summary.textContent=`會員 ${rows.length} 人｜待審核 ${counts.pending||0}｜已啟用 ${counts.active||0}｜已停權 ${counts.suspended||0}`; }
  async function load(){ if(!session)return; if(summary)summary.textContent='讀取會員資料中…'; try{rows=await A.listProfiles(session); render();}catch(e){console.error(e); if(summary)summary.textContent=`讀取失敗：${e.message||e}`;} }
  async function save(tr,btn){ const id=tr.dataset.id, status=tr.querySelector('[data-field="status"]').value, plan=tr.querySelector('[data-field="plan"]').value, starts=tr.querySelector('[data-field="starts_at"]').value, expEl=tr.querySelector('[data-field="expires_at"]'), expires=plan==='permanent'?null:expEl.value; btn.disabled=true;btn.textContent='儲存中…'; try{await A.updateProfile(session,id,{status,plan,starts_at:starts?new Date(`${starts}T00:00:00`).toISOString():null,expires_at:expires?new Date(`${expires}T23:59:59`).toISOString():null,updated_at:new Date().toISOString()}); btn.textContent='已儲存'; await load();}catch(e){alert(`儲存失敗：${e.message||e}`);btn.disabled=false;btn.textContent='儲存';} }
  async function start(){ if(started||!window.TIANSHU_MEMBER?.profile)return; started=true; session=await A.getSession(); currentUserId=session?.user?.id||null; searchInput?.addEventListener('input',render); statusFilter?.addEventListener('change',render); planFilter?.addEventListener('change',render); tbody?.addEventListener('change',e=>{if(e.target.matches('[data-field="plan"]')){const tr=e.target.closest('tr'),exp=tr.querySelector('[data-field="expires_at"]');exp.disabled=e.target.value==='permanent';if(exp.disabled)exp.value='';}}); tbody?.addEventListener('click',e=>{const b=e.target.closest('.admin-save-btn');if(b)save(b.closest('tr'),b);}); document.querySelector('#adminRefresh')?.addEventListener('click',load); load(); }
  window.addEventListener('tianshu:member-ready',start,{once:true});
  if(window.TIANSHU_MEMBER?.profile)start();
})();
